# Generated by Django 4.0 on 2021-12-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vgSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank', models.IntegerField(default=0)),
                ('Name', models.CharField(max_length=200)),
                ('Platform', models.CharField(max_length=200)),
                ('Year', models.IntegerField(null=True)),
                ('Genre', models.CharField(max_length=100)),
                ('Publisher', models.CharField(max_length=200)),
                ('NA_Sales', models.FloatField()),
                ('EU_Sales', models.FloatField()),
                ('JP_Sales', models.FloatField()),
                ('Other_Sales', models.FloatField()),
                ('Global_Sales', models.FloatField()),
            ],
        ),
    ]
