# Generated by Django 3.2.9 on 2021-11-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vgSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Platform', models.CharField(max_length=200)),
                ('Year', models.IntegerField(null=True)),
                ('Genre', models.CharField(max_length=100)),
                ('Publisher', models.CharField(max_length=200)),
                ('NA_Sales', models.FloatField()),
                ('EU_Sales', models.FloatField()),
                ('JP_Sales', models.FloatField()),
                ('Other_Sales', models.FloatField()),
                ('Global_Sales', models.FloatField()),
            ],
        ),
    ]
